import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { ShoppingCart, Check, Copy, Download, Plus } from 'lucide-react'
import toast from 'react-hot-toast'

const GroceryList = ({ items }) => {
  const [checkedItems, setCheckedItems] = useState(new Set())

  const toggleCheck = (item) => {
    const newChecked = new Set(checkedItems)
    if (newChecked.has(item)) {
      newChecked.delete(item)
    } else {
      newChecked.add(item)
    }
    setCheckedItems(newChecked)
  }

  const copyToClipboard = async () => {
    try {
      const listText = items.map(item => `• ${item}`).join('\n')
      await navigator.clipboard.writeText(listText)
      toast.success('Grocery list copied to clipboard!')
    } catch (error) {
      toast.error('Failed to copy to clipboard')
    }
  }

  const downloadList = () => {
    const listText = `Grocery List\n\n${items.map(item => `• ${item}`).join('\n')}\n\nGenerated by AI Recipe Generator`
    const blob = new Blob([listText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'grocery-list.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Grocery list downloaded!')
  }

  if (!items || items.length === 0) {
    return null
  }

  return (
    <motion.div
      id="grocery-section"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className="bg-white/80 backdrop-blur-sm rounded-3xl p-8 shadow-xl border border-white/50"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="bg-gradient-to-r from-secondary-500 to-primary-500 p-3 rounded-xl">
            <ShoppingCart className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-gray-800">Shopping List</h2>
            <p className="text-gray-600">Items you need to complete your recipes</p>
          </div>
        </div>
        
        <div className="flex space-x-3">
          <button
            onClick={copyToClipboard}
            className="flex items-center space-x-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium py-2 px-4 rounded-xl transition-all duration-200"
          >
            <Copy className="w-4 h-4" />
            <span className="hidden sm:inline">Copy</span>
          </button>
          <button
            onClick={downloadList}
            className="flex items-center space-x-2 bg-primary-500 hover:bg-primary-600 text-white font-medium py-2 px-4 rounded-xl transition-all duration-200"
          >
            <Download className="w-4 h-4" />
            <span className="hidden sm:inline">Download</span>
          </button>
        </div>
      </div>

      {/* Statistics */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        <div className="bg-gradient-to-r from-blue-50 to-blue-100 p-4 rounded-xl border border-blue-200">
          <div className="flex items-center space-x-2">
            <ShoppingCart className="w-5 h-5 text-blue-600" />
            <div>
              <p className="text-2xl font-bold text-blue-800">{items.length}</p>
              <p className="text-sm text-blue-600">Total Items</p>
            </div>
          </div>
        </div>
        
        <div className="bg-gradient-to-r from-green-50 to-green-100 p-4 rounded-xl border border-green-200">
          <div className="flex items-center space-x-2">
            <Check className="w-5 h-5 text-green-600" />
            <div>
              <p className="text-2xl font-bold text-green-800">{checkedItems.size}</p>
              <p className="text-sm text-green-600">Checked Off</p>
            </div>
          </div>
        </div>
        
        <div className="bg-gradient-to-r from-orange-50 to-orange-100 p-4 rounded-xl border border-orange-200">
          <div className="flex items-center space-x-2">
            <Plus className="w-5 h-5 text-orange-600" />
            <div>
              <p className="text-2xl font-bold text-orange-800">{items.length - checkedItems.size}</p>
              <p className="text-sm text-orange-600">Remaining</p>
            </div>
          </div>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium text-gray-700">Shopping Progress</span>
          <span className="text-sm text-gray-600">
            {Math.round((checkedItems.size / items.length) * 100)}% complete
          </span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
          <motion.div
            className="bg-gradient-to-r from-green-400 to-green-500 h-3 rounded-full"
            initial={{ width: 0 }}
            animate={{ width: `${(checkedItems.size / items.length) * 100}%` }}
            transition={{ duration: 0.5, ease: "easeOut" }}
          />
        </div>
      </div>

      {/* Grocery Items */}
      <div className="space-y-3">
        {items.map((item, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.3, delay: index * 0.05 }}
            className={`flex items-center space-x-4 p-4 rounded-xl border transition-all duration-200 ${
              checkedItems.has(item)
                ? 'bg-green-50 border-green-200 opacity-60'
                : 'bg-white border-gray-200 hover:border-primary-300 hover:shadow-md'
            }`}
          >
            <button
              onClick={() => toggleCheck(item)}
              className={`flex items-center justify-center w-6 h-6 rounded-full border-2 transition-all duration-200 ${
                checkedItems.has(item)
                  ? 'bg-green-500 border-green-500 text-white'
                  : 'border-gray-300 hover:border-primary-500'
              }`}
            >
              {checkedItems.has(item) && <Check className="w-4 h-4" />}
            </button>
            
            <div className="flex-1">
              <span className={`font-medium transition-all duration-200 ${
                checkedItems.has(item) 
                  ? 'text-gray-500 line-through' 
                  : 'text-gray-800'
              }`}>
                {item}
              </span>
            </div>

            <div className="text-sm text-gray-500">
              #{index + 1}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 p-4 bg-gradient-to-r from-primary-50 to-secondary-50 rounded-xl border border-primary-100">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm font-medium text-gray-800">Happy Shopping! 🛒</p>
            <p className="text-xs text-gray-600">Don't forget to check for sales and substitutes</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-primary-600">
              {checkedItems.size}/{items.length} items
            </p>
            <p className="text-xs text-gray-600">collected</p>
          </div>
        </div>
      </div>
    </motion.div>
  )
}

export default GroceryList